/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGraphRouteImport } from './routes/_authenticated/graph'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes.index'
import { Route as AuthenticatedNotesNewRouteImport } from './routes/_authenticated/notes.new'
import { Route as AuthenticatedNotesNoteIdRouteImport } from './routes/_authenticated/notes.$noteId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGraphRoute = AuthenticatedGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesNewRoute = AuthenticatedNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesNoteIdRoute =
  AuthenticatedNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/graph': typeof AuthenticatedGraphRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/_authenticated/notes/new': typeof AuthenticatedNotesNewRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/graph'
    | '/insights'
    | '/notes/$noteId'
    | '/notes/new'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/graph'
    | '/insights'
    | '/notes/$noteId'
    | '/notes/new'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/graph'
    | '/_authenticated/insights'
    | '/_authenticated/notes/$noteId'
    | '/_authenticated/notes/new'
    | '/_authenticated/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/graph': {
      id: '/_authenticated/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/new': {
      id: '/_authenticated/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AuthenticatedNotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGraphRoute: typeof AuthenticatedGraphRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute
  AuthenticatedNotesNewRoute: typeof AuthenticatedNotesNewRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGraphRoute: AuthenticatedGraphRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
  AuthenticatedNotesNewRoute: AuthenticatedNotesNewRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
