// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pohpuzfbgagikwmbfktp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvaHB1emZiZ2FnaWt3bWJma3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NTIzMjMsImV4cCI6MjA5NTAyODMyM30.AD5I-D4pxiWsJ9D_tBTHPZKDbZILE6LZiyoqlMeqFBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});